#ifndef JOBSERVER_FREE_TOKEN
#define JOBSERVER_FREE_TOKEN (char)0
#endif

#ifndef JOBSERVER_SIZE_GEOME_PROG
#define JOBSERVER_SIZE_GEOME_PROG 2
#endif

#ifndef JOBSERVER_SIZE_ARITH_PROG
#define JOBSERVER_SIZE_ARITH_PROG 8
#endif

#ifndef MAKEFLAGS
#define MAKEFLAGS "MAKEFLAGS"
#endif

#ifndef MAKEFLAGS_JOBSERVER
#define MAKEFLAGS_JOBSERVER "--jobserver-auth"
#endif
